export const ADD_CANDIDATES = "ADD_CANDIDATES";
export const ADD_TO_SHORTLIST = "ADD_TO_SHORTLIST";
export const ADD_TO_REJECTLIST = "ADD_TO_REJECTLIST";
export const ADD_SEARCH_RESULT = "ADD_SEARCH_RESULT";
